kubos/kubos

- docs/services/graphql.rst
Adds some copy tweaks and a GraphQL example.
> Copy changes and GraphQL example

- eps/nanopower-api/source/nanopower.c
- eps/nanopower-api/test/nanopower/nanopower.c
- eps/nanopower-api/test/nanopower/stubs.cmake
- eps/nanopower-api/test/nanopower/sysfs.c
- hal/kubos-hal/source/i2c.c
- test/integration/linux/nanopower-p31u/README.md
- test/integration/linux/nanopower-p31u/module.json
- test/integration/linux/nanopower-p31u/source/main.c
Adding unit tests and an integration test for the NanoPower API
> Testing for NanoPower API

- clients/shell-client/main.lua
- clients/shell-client/package.lua
- libs/cbor-message-protocol.lua
- services/shell-service/init.lua
- services/shell-service/libs/channel-service.lua
- services/shell-service/package.lua
This extracts the common CBOR and back-pressure logic used by file and shell services into a shared library.
> Make cbor based protocols more reliable

- hal/rust-hal/rust-uart/src/lib.rs
This PR basically addresses and fixes the issue raised in #76.
> SerialStream fix for Rust UART HAL 

- services/novatel-oem6-service/src/tests/schema/mutations/errors.rs
- services/novatel-oem6-service/src/tests/schema/queries/errors.rs
The parent branch has a couple failing unit tests, but it's a massive PR, so I made a new PR with the fixes
> OEM6 Service Fixes

- docs/dev-docs/changelog.rst
- docs/index.rst
Creating the changelog notes for the v1.3 release.
Also adding Stable/Nightly docs link to docs home page
> Changelog for v1.3

- .gitignore
- docs/apis/kubos-hal/i2c-hal/rust-i2c.rst
- docs/architecture-overview.rst
- docs/installation-docs/sdk-installing.rst
- docs/os-docs/index.rst
- docs/sdk-docs/index.rst
- docs/services/graphql.rst
- docs/services/payload-services.rst
- docs/what-is-a-mission-application.rst
Here are some minor fixes to typos in the docs that I found as I was reading through them.
> Minor docs fixes

- services/file-service-rust/tests/upload.rs
And by fixing, I mean covering up...
> Fixing multi-client upload test case

- Cargo.lock
- clients/file-client/Cargo.toml
- clients/file-client/src/main.rs
- libs/cbor-protocol/Cargo.toml
- libs/cbor-protocol/src/lib.rs
- libs/file-protocol/Cargo.toml
- libs/file-protocol/src/error.rs
- libs/file-protocol/src/lib.rs
- libs/file-protocol/src/messages.rs
- libs/file-protocol/src/parsers.rs
- libs/file-protocol/src/protocol.rs
- libs/file-protocol/src/storage.rs
- services/file-service/Cargo.toml
- services/file-service/src/lib.rs
- services/file-service/tests/download.rs
- services/file-service/tests/upload.rs
> Convert file protocol error handling to failure

- libs/file-protocol/src/error.rs
- libs/file-protocol/src/protocol.rs
- libs/file-protocol/src/storage.rs
- services/file-service/tests/download.rs
- services/file-service/tests/upload.rs
- Clean up after a corrupt chunk
- Clean up after a hash mismatch
> File protocol clean up

- clients/file-client/src/main.rs
- docs/services/file.rst
- libs/cbor-protocol/src/lib.rs
- libs/file-protocol/src/lib.rs
- libs/file-protocol/src/protocol.rs
- libs/file-protocol/src/storage.rs
- services/file-service/src/lib.rs
- services/file-service/tests/common/mod.rs
- services/file-service/tests/download.rs
- services/file-service/tests/upload.rs
- services/file-service/tests/variable_chunks.rs
> Making the file protocol more configurable

- services/file-service/src/main.rs
- services/telemetry-service/tests/test_udp.rs
Also tweaking telemetry db service direct udp unit tests to extend delay between the test and the verification steps
> Fixing file transfer service logging location

- services/telemetry-service/tests/test_delete.rs
Somehow missed that I didn't properly commit this unit test file when I was working on #178
> Adding delete mutation unit tests

- Cargo.lock
- libs/channel-protocol/src/protocol.rs
- libs/shell-protocol/Cargo.toml
- libs/shell-protocol/src/error.rs
- libs/shell-protocol/src/lib.rs
- libs/shell-protocol/src/messages/kill.rs
- libs/shell-protocol/src/messages/list.rs
- libs/shell-protocol/src/messages/mod.rs
- libs/shell-protocol/src/process.rs
- libs/shell-protocol/src/protocol.rs
- services/shell-service-rust/src/lib.rs
Added handling for list and kill messages.
> Shell protocol - listing & killing

- libs/file-protocol/src/protocol.rs
- services/file-service/tests/upload.rs
- Fixes file client reporting positive if upload files
- Fixes bug in file service upload_single* tests
> File transfer false positive bug

- Cargo.lock
- services/kubos-service/Cargo.toml
- services/kubos-service/src/lib.rs
- services/kubos-service/src/service.rs
- services/monitor-service/Cargo.toml
- services/monitor-service/src/main.rs
Also updating the `kubos-service` crate to use the base `log` crate's macros
> Adding logging setup to monitor service

- apis/pumpkin-mcu-api/mcu_api.py
- apis/pumpkin-mcu-api/test_mcu_api.py
- services/iobc-supervisor-service/src/model.rs
- services/kubos-service/src/macros.rs
- services/mai400-service/src/model.rs
- services/novatel-oem6-service/src/model.rs
- services/pumpkin-mcu-service/service/schema.py
- services/telemetry-service/src/schema.rs
- services/telemetry-service/src/udp.rs
Adding log lines to record any errors encountered in our services.
Mostly this is done by updating the `push_err` macro to write whatever error to the logger.
> Service logging

- docs/app-docs/app-service.rst
- services/app-service/src/error.rs
- services/app-service/src/registry.rs
- services/app-service/src/tests/registry_onboot.rs
- services/app-service/src/tests/registry_start_app.rs
Updating the app service to wait a moment after kicking off an application to see if it immediately fails or not.
> Adding try/wait logic to app service

- CONTRIBUTING.md
- docs/dev-docs/contribution-process.rst
- docs/index.rst
- docs/sdk-docs/index.rst
Mostly cleaning up some outdated links
> Doc tweaks

- docs/installation-docs/installing-linux-iobc.rst
- docs/os-docs/configuring-kubos.rst
- docs/os-docs/kubos-linux-on-bbb.rst
- docs/os-docs/kubos-linux-on-iobc.rst
- docs/os-docs/kubos-linux-on-mbm2.rst
Doc updates which correspond with kubos/kubos-linux-build#169
> Updating Buildroot docs for new LTS version

- .github/ISSUE_TEMPLATE/feature_request.md
This is almost exactly GitHub's default feature request template.
I'm not really sure what we'd want that's different.
> Add Feature Request Template

- docs/architecture-overview.rst
- docs/kubos-design.rst
Still have some stuff to write, but I'd like some feedback on the direction I'm going. What do y'all think?
> Architecture doc

- docs/getting-started/local-setup.rst
- tools/kubos_verify.sh
This document lays out how to setup the local development environment for linux & osx
> Local development setup doc

- docs/getting-started/local-services.rst
- tools/default_config.toml
This document discussing configuring and running services in a local environment.
> Local services doc

- docs/getting-started/local-setup.rst
- docs/tutorials/first-mission-app.rst
- docs/tutorials/first-obc-project.rst
Fix some paths and move `SERVICES = app_api.services()` into the conditional because otherwise it crashes with `No such file or directory: /home/system/etc/config.toml` (a default I assume).
A deeper issue is that I cannot use use the example app because `mem_info` does not work on a Mac (no `proc` filesystem). This script does work, albeit with fake data:
```python
#!/usr/bin/env python3
import argparse
import app_api
import sys
def on_boot():
print("OnBoot logic")
def on_command():
request = '{ping}'
try:
response = SERVICES.query(service="monitor-service", query=request)
except Exception as e:
print("Something went wrong: " + str(e))
sys.exit(1)
data = response["ping"]
print("Response: %s" % (data))
request = '''
mutation {
insert(subsystem: "OBC", parameter: "available_mem", value: …
```
> Minor cleanup on first-mission-app

- docs/deep-dive/design-decisions.rst
- docs/kubos-design.rst
- docs/mission-dev/index.rst
New section under mission needs for payload integration.
Linked real time section to design decisions.
> Doc Review changes 

- apis/app-api/python/requirements.txt
- apis/pumpkin-mcu-api/requirements.txt
- examples/pumpkin-mcu-api-example/requirements.txt
- examples/python-mission-application/requirements.txt
- examples/python-mission-framework/requirements.txt
- examples/python-service/requirements.txt
- hal/python-hal/i2c/requirements.txt
- libs/kubos-service/optional-requirements.txt
- libs/kubos-service/requirements.txt
- libs/kubos-test/kubos_test.py
- libs/kubos-test/requirements.txt
- requirements.txt
- services/pumpkin-mcu-service/requirements.txt
The intention is that you can install all dependencies by running `pip3 install -r requirements.txt` from the repo's root directory
Most packages are version locked based on the version being used by Buildroot
> Updating all Python package requirements.txt files

- tools/dist/Dockerfile
Fixing a version mismatch with the nos boost dependency.
> Fixing nos docker boost

- Cargo.lock
- docs/ecosystem/services/scheduler.rst
- services/scheduler-service/Cargo.toml
- services/scheduler-service/src/app.rs
- services/scheduler-service/src/main.rs
- services/scheduler-service/src/scheduler.rs
- services/scheduler-service/src/schema.rs
- services/scheduler-service/src/task_list.rs
- services/scheduler-service/tests/import_raw.rs
- services/scheduler-service/tests/init.rs
- services/scheduler-service/tests/onetime.rs
- services/scheduler-service/tests/recurring.rs
- services/scheduler-service/tests/util/mod.rs
- tools/local_config.toml
> Adding raw task import and other enhancements

- services/scheduler-service/tests/util/mod.rs
- utils/src/testing.rs
Chasing down random unit test failures
> [WIP] Scheduler test fixes

- docs/tutorials/first-mission-app.rst
Some suggestions/typo fixes from going through the tutorials.
> Tutorial updates

- services/app-service/src/registry.rs
There is an issue creating symlinks in the `active` dir when the base `apps_dir` is a relative path. This ensures that `apps_dir` is always an absolute path.
> Fixing relative app-registry paths

- docs/tutorials/querying-telemetry.rst
- docs/tutorials/schedule-app.rst
> Minor tutorial fixes

- docs/deep-dive/klb/configuring-kubos.rst
- docs/deep-dive/klb/kubos-linux-on-bbb.rst
- docs/deep-dive/klb/kubos-linux-on-iobc.rst
- docs/deep-dive/klb/kubos-linux-on-mbm2.rst
Companion PR to kubos/kubos-linux-build#205
> Adding instructions for changing KubOS version in KLB

- docs/kubos-design.rst
document the response to a question answered by @tbrowder1 on slack regarding the meaning of colors in the diagram and also adds alt text to the figure.
> Add some clarification to the colors used in the "Kubos Design" diagram
