- docs/dev-docs/changelog.rst
- hal/kubos-hal-iobc/Cargo.lock
- hal/kubos-hal-iobc/Cargo.toml
- hal/kubos-hal-iobc/build.rs
- hal/kubos-hal-iobc/src/ffi.rs
- hal/kubos-hal-iobc/src/lib.rs
- Create FFI interface to C-based supervisor functions
- Create proper Rust interfaces to wrap around FFI functions
- Tests to ensure valid data conversion
> Adding Rust wrapper for kubos-hal-iobc

- examples/adc-thermistor/README.md
- examples/adc-thermistor/module.json
- tools/dist/Dockerfile
Fixing a few kubostech->kubos stragglers.
Note: There are two places where "kubostech" will still exist
1. In the changelog with the links to old JIRA stories
2. In our CLA link (https://www.clahub.com/agreements/kubostech/KubOS)
> Kubostech->kubos name change cleanup

- hal/kubos-hal-linux/source/i2c.c
- libcsp/docs/Doxyfile
- libcsp/include/csp/csp_types.h
There are two legacy warnings which pop up when running `gendocs.py`. This PR is fixing them.
```
/home/vagrant/sharedOS/hal/kubos-hal-linux/source/i2c.c:38: warning: Member STRINGIFY(s) (macro definition) of group LINUX_HAL_I2C is not documented.
/home/vagrant/sharedOS/hal/kubos-hal-linux/source/i2c.c:39: warning: Member TOSTRING(s) (macro definition) of group LINUX_HAL_I2C is not documented.
```
and
```
/home/vagrant/sharedOS/docs/apis/libcsp/types.rst:4: WARNING: Invalid definition: Expected identifier in nested name. [error at 17]
struct csp_id_t::@7 csp_id_t::@8
-----------------^
```
> Clearing doc gen warnings

- Cargo.lock
- hal/rust-hal/rust-uart/Cargo.toml
- hal/rust-hal/rust-uart/src/error.rs
- hal/rust-hal/rust-uart/src/lib.rs
- hal/rust-hal/rust-uart/src/mock.rs
- hal/rust-hal/rust-uart/src/tests.rs
This PR adds a few features which I found that I needed while working on the NovAtel OEM6 API in kubos#74:
- Updated `Connection::from_path` to have two new parameters: settings and timeout.
- [Failure](https://github.com/rust-lang-nursery/failure) is our error-handling crate-of-choice, so converted the current error type into a Failure error type
- Changed the code to open the connection to the serial port once, during the `SerialStream::new()` call, rather than during each `write()` and `read()` call, so that messages which require multiple read calls (ex. where we need to read a header to then get the length of the whole message) will work
- Tweaked the `read` calls to add a timeout parameter. There's currently no way to do an indefinite `read` call with the [serial …
> Rust UART HAL Updates

- apis/novatel-oem6-api/src/lib.rs
- apis/novatel-oem6-api/src/messages/logs/best_xyz.rs
- apis/novatel-oem6-api/src/messages/logs/mod.rs
- apis/novatel-oem6-api/src/messages/logs/rxstatusevent.rs
- apis/novatel-oem6-api/src/messages/logs/version.rs
- apis/novatel-oem6-api/src/messages/mod.rs
- apis/novatel-oem6-api/src/oem6.rs
- apis/novatel-oem6-api/src/tests/errors.rs
- apis/novatel-oem6-api/src/tests/position.rs
- apis/novatel-oem6-api/src/tests/version.rs
- services/novatel-oem6-service/src/model.rs
- services/novatel-oem6-service/src/objects.rs
- services/novatel-oem6-service/src/schema.rs
- services/novatel-oem6-service/src/tests/schema/mutations/noop.rs
- services/novatel-oem6-service/src/tests/schema/mutations/test_hardware.rs
- services/novatel-oem6-service/src/tests/schema/queries/power.rs
- services/novatel-oem6-service/src/tests/schema/queries/system_status.rs
- services/novatel-oem6-service/src/tests/schema/queries/test_results.rs
Adding queries:
- `power`
- `systemStatus`
Additional work:
- Converted the message header `recv_status` field from a raw u32 into bit fields
- Added system time, time status, and receiver status to all log messages in the API. They're not all used for each log within the service, but they're useful fields to have in general
- There a several functions which get and use the VersionInfo log. Changed the code to make one central `get_version_log()` function
> OEM6 Service: Phase 4

- services/kubos-service/src/service.rs
- services/novatel-oem6-service/Cargo.toml
- services/novatel-oem6-service/src/main.rs
- services/novatel-oem6-service/src/model.rs
- services/novatel-oem6-service/src/objects.rs
- services/novatel-oem6-service/src/schema.rs
- services/novatel-oem6-service/src/tests/mod.rs
- services/novatel-oem6-service/src/tests/schema/mod.rs
- services/novatel-oem6-service/src/tests/schema/mutations/test_hardware.rs
- services/novatel-oem6-service/src/tests/schema/queries/telemetry.rs
- services/novatel-oem6-service/src/tests/schema/queries/test_results.rs
- Adding `telemetry` query.
- Under the covers, adding nominal telemetry, which is also returned by `testHardware(INTEGRATION)` and `testResults`
- Adding full schema to main doc
> OEM6 Service: Phase 5

- services/novatel-oem6-service/src/main.rs
- services/novatel-oem6-service/src/model.rs
- services/novatel-oem6-service/src/tests/schema/mutations/test_hardware.rs
- services/novatel-oem6-service/src/tests/schema/queries/test_results.rs
Hard coding things is bad. Pulling the bus device (ex. "/dev/ttyS4") from the master config.toml file
> Adding OEM6 bus configuration

- docs/services/core-services.rst
- tools/gendocs.py
Our new Rust crates have lots of documentation which should be included in our official docs. This PR starts to integrate them by using Rust's doc gen (via `cargo kubos -c doc` to handle our custom C/Rust combo crates) and then copying the resulting HTML files into our usual `html` output folder.
Our existing docs are then able to reference them using relative links. An example has been included in this PR.
For an example doc link: http://docs.kubos.co/beta/services/core-services.html
To look at all the Rust docs: http://docs.kubos.co/beta/rust-docs/telemetry_service/index.html
Notes: 
- I looked at [Doxidize](https://github.com/steveklabnik/doxidize), but was unable to get it to quickly work. It's a very new tool, so might still be good to return to at some point.
- There isn't currently …
> Adding Rust doc generation to gendocs.py

- docs/os-docs/using-kubos-linux.rst
- docs/os-docs/working-with-the-bbb.rst
- docs/os-docs/working-with-the-iobc.rst
- docs/os-docs/working-with-the-mbm2.rst
- docs/sdk-docs/sdk-examples.rst
- docs/sdk-docs/sdk-project-config.rst
- docs/sdk-docs/sdk-rust.rst
- Making the examples page just refer to the 'examples' folder of the repo, rather than explaining each available example
- Adding instructions to the examples page on how to use the Rust and Python example projects
- Updating the Rust SDK instructions to cover the normal `cargo build` process
- Fixing all our system path locations to actually be correct... >.>
- Fixing some I2C HAL links which I missed
> SDK Doc Updates

- circle.yml
Our current Circle configuration will not run when release tags are generated. This requires us to manually run the docs generation step for each release. These changes should instruct Circle to just regenerate and publish the docs when a new release (`x.y.x` *not* `x.y.z+abc`) tag is made. Following configuration instructions from here - https://circleci.com/docs/1.0/configuration/#tags.
> Added new circleci step to regenerate just the docs on a release tag.

- docs/installation-docs/installing-linux-bbb.rst
- docs/installation-docs/installing-linux-mbm2.rst
- docs/os-docs/kubos-linux-on-bbb.rst
- docs/os-docs/kubos-linux-on-mbm2.rst
The auxiliary SD card image for BBB and MBM2 is now automatically generated as part of the build process (kubos/kubos-linux-build#106). Updating the docs to reflect that.
> Updating aux-sd gen docs

- apis/app-api/rust/src/query.rs
Currently, when the Rust `kubos-service` crate processes a good graphql request, it returns `{"errs": "", "msg": {response data}}`, while the Python version returns `{"errs": null, "msg": {response}}`.
This PR updates the Rust `query()` function to allow either format.
> Allowing `"Errs": null` in GraphQL Response

- apis/clyde-3g-eps-api/Cargo.toml
- apis/system-api/Cargo.toml
The Rust `failure` crate is changing ownership and the in-progress `1.0` version has now been deprecated. This breaks two of our crates. I'm simply removing the version requirement for now.
Note: This is a bandaid fix. There will likely be breaking changes in the `failure` crate in the future, which we'll need to handle.
> Removing failure version requirement

- tools/dist/Dockerfile
Update the location of the `*_toolchain.tar.gz` packages.
Goes along with https://github.com/kubos/kubos-vagrant/pull/47.
> Update S3 asset location

- Cargo.lock
- clients/file-client/src/main.rs
- docs/services/file-protocol.rst
- libs/cbor-protocol/src/lib.rs
- libs/file-protocol/Cargo.toml
- libs/file-protocol/src/lib.rs
- libs/file-protocol/src/messages.rs
- libs/file-protocol/src/parsers.rs
- libs/file-protocol/src/protocol.rs
- libs/file-protocol/src/storage.rs
- services/file-service/Cargo.toml
- services/file-service/src/lib.rs
- services/file-service/tests/download.rs
- services/file-service/tests/upload.rs
The threading model of the file service has been updated to better support multiple simultaneous clients uploading or downloading files. This has also relieved the need for most non-timeout related delays in the protocol implementation :tada:.
Other majorish changes:
- Content addressable messages (metadata, chunk, ack, nak) now include the channel id as first parameter
- Channel ids moved from `u64` -> `u32`
> File Service Threading Update

- docs/app-docs/app-service.rst
- docs/tutorials/app-register.rst
- examples/python-mission-application/manifest.toml
- services/app-service/src/objects.rs
- services/app-service/src/registry.rs
- services/app-service/src/schema.rs
- services/app-service/src/tests/mod.rs
- services/app-service/src/tests/register_app.rs
- services/app-service/src/tests/registry_onboot.rs
- services/app-service/src/tests/upgrade_app.rs
Currently it is possible to upgrade applications with the applications service by simply re-registering them. However, this only works if the application name remain the same.
The original intention was that the application name could be changed between versions and the application UUID would be used as the main identifier.
This PR updates the `register` mutation to allow a UUID to be passed in order to upgrade an existing application. The documentation has also been updated to reflect the changes.
> Adding the ability to upgrade applications

- Cargo.lock
- apis/app-api/rust/src/framework.rs
- apis/app-api/rust/src/lib.rs
- examples/rust-mission-app/Cargo.toml
- examples/rust-mission-app/src/main.rs
Adding `Result<(), Error>` to the AppHandler trait's functions.
This can be more properly tested once the app service is updated to wait a moment to check for app execution issues.
> Adding return codes to Rust app API

- docs/tutorials/first-mission-app.rst
- examples/python-mission-application/mission-app.py
Adding non-zero exit codes to the example Python mission app and the corresponding tutorial. This will become more important once the app service is capable of checking a started app's return code
> Adding bad exit code to Python app example and tutorial

- Cargo.lock
- apis/telemetry-db-api/src/lib.rs
- apis/telemetry-db-api/src/models.rs
- services/telemetry-service/Cargo.toml
- services/telemetry-service/src/schema.rs
- services/telemetry-service/src/udp.rs
- services/telemetry-service/tests/test_delete.rs
- services/telemetry-service/tests/test_filter_subsystem.rs
- services/telemetry-service/tests/test_insert.rs
- services/telemetry-service/tests/test_limit.rs
- services/telemetry-service/tests/test_route.rs
- services/telemetry-service/tests/test_select_all.rs
- services/telemetry-service/tests/test_udp.rs
- test/benchmark/db-test/src/main.rs
Milliseconds since unix epoch overflowed the current i32 storage size. GraphQL (and Juniper) doesn't support i64, meaning the next biggest available data size is f64.
As a result, the telem db timestamps have been updated to use fractional seconds
> Expanding timestamp size to be a Double. Change units to seconds

- Cargo.lock
- services/shell-service/Cargo.toml
- services/shell-service/src/lib.rs
- services/shell-service/src/main.rs
This is my plan for how all the services will be updated to use syslog for logging.
Worth noting, this does remove the terminal logger component. This behavior can be re-added by the user by setting up a logging policy which routes the messages to the console (or some similar policy):
`daemon.*    /dev/console`
> Converting shell service to use syslog for logging

- apis/app-api/rust/src/query.rs
- services/app-service/src/tests/register_app.rs
- services/app-service/src/tests/registry_start_app.rs
- services/app-service/src/tests/upgrade_app.rs
- services/file-service/tests/upload.rs
- services/isis-ants-service/src/tests/mod.rs
- services/kubos-service/src/service.rs
- services/mai400-service/src/tests/read.rs
- services/mai400-service/src/tests/schema.rs
- services/novatel-oem6-service/src/tests/schema/mod.rs
- services/telemetry-service/tests/test_delete.rs
- services/telemetry-service/tests/test_empty_db.rs
- services/telemetry-service/tests/test_filter_parameter.rs
- services/telemetry-service/tests/test_filter_subsystem.rs
- services/telemetry-service/tests/test_filter_timestamp.rs
- services/telemetry-service/tests/test_insert.rs
- services/telemetry-service/tests/test_limit.rs
- services/telemetry-service/tests/test_route.rs
- services/telemetry-service/tests/test_select_all.rs
- services/telemetry-service/tests/test_udp.rs
Updating our GraphQL responses to [match the spec](https://facebook.github.io/graphql/June2018/#sec-Response-Format)
- "msg" -> "data"
- "errs" -> "errors"
- Updated the case where an error is hit before any data is generated to return the errors array in an object, rather than just an array
> Updating GraphQL responses to match spec

- Cargo.lock
- docs/app-docs/app-guide.rst
- docs/app-docs/app-service.rst
- services/app-service/Cargo.toml
- services/app-service/src/main.rs
- services/app-service/src/registry.rs
- services/app-service/src/tests/register_app.rs
Currently, the app service expects exactly two files to be present in the directory used to register an application: the `manifest.toml` file and the executable.
For Python applications, there is no executable, so it's entirely likely that users will want to register an application with more than one file.
This PR changes the registration logic to copy the entire contents of the directory specified when registering an app
> Allowing multiple files to be present in app registry dir

- services/telemetry-service/tests/test_route.rs
Two of the tests in `services/telemetry-service/tests/test_route.rs` use a non-temporary file with the same name. This file is then removed at the end of each test so that it can be repeatable.
This is causing problems when run by CircleCI (some sort of timing problem. I was unable to reproduce it locally).
This PR fixes the test cases so they each have a unique test file
> Fixing duplicate telemetry service test file name

- Cargo.lock
- libs/comms-service/Cargo.toml
- libs/comms-service/src/config.rs
- libs/comms-service/src/lib.rs
- services/ethernet-service/Cargo.toml
- services/ethernet-service/src/comms.rs
- services/ethernet-service/src/main.rs
Currently the communication service library expects the comms settings to be established in a custom config.toml file
This PR updates the library to use the standard config.toml file provided by the `kubos-system` crate (apis/system-api)
Also updates the config reading logic to take advantage of `Deserialize` to convert the `toml::Value` into a `CommsConfig` structure, rather than needing to explicitly parse all the args
> Moving communications settings into main toml file

- apis/app-api/python/app_api.py
- prep_docs.sh
- Fixing python app api doc generation. Sphinx can auto-generate docs based on the code documentation, but the app api needs to be in the system path. So, I updated the `prep-docs.sh` script to do the installation before making the `sphinx-build` call
- Adding some actual code documentation
> Updating Python App API Documentation

- docs/apis/kubos-hal/uart-hal/rust-uart.rst
The rust uart hal doc link available [here](https://docs.kubos.com/1.11.0/apis/kubos-hal/uart-hal/rust-uart.html) is broken. Fixing it
> Fixing Rust UART HAL doc link

- apis/isis-trxvu-api/isis-trxvu-api/trxvu.h
- apis/isis-trxvu-api/source/radio_core.c
- apis/isis-trxvu-api/source/radio_rx.c
- apis/isis-trxvu-api/source/radio_tx.c
- apis/isis-trxvu-api/test/radio/radio.c
- docs/apis/device-api/isis-trxvu/trxvu.rst
- test/integration/linux/isis-trxvu/radio-test/source/main.c
The TRXVU API is the last place where the old YOTTA_CONFIG_* options are used. Converting them to run-time arguments instead
> Converting TRXVU yotta config options to run-time arguments

- apis/app-api/python/app_api.py
- examples/pumpkin-mcu-api-example/example_mcu_api.py
- examples/python-service/service.py
- examples/python-service/service/app.py
- examples/python-service/service/models.py
- examples/python-service/service/schema.py
- libs/kubos-service/kubos_service/udp_service.py
Migrating all the application-related code and our boiler-plate service code to Python3.5 (this is what's included with our current version of BuildRoot). I tested the new code against both Python3.5 and our current Python2.7 and it seems like the new code is backwards-compatible.
Most of the changes are just updating the `print` syntax.
Most notable is the way strings are declared/handled:
- Python 2.7 `str` -> 3.5 `bytes`
- 2.7 `unicode` -> 3.5 `str`
- `bytes` in 2.7 is just an alias to `str`
- `unicode` does not exist at all in 3.5
The mission app examples didn't need to be updated
Also, tweaking the kubos service framework to correctly set up logging
> Migrating to Python3

- .circleci/config.yml
This will add `cargo check` for the mbm2 and iobc targets to our CI.
> Added CI cross compiling checks

- tools/dist/Dockerfile
We need `pkg-config` and `libssl-dev` for the new HTTP services
(Both are already available in our Vagrant image)
> Adding pkg-config to Docker

- .circleci/config.yml
- Cargo.lock
- apis/app-api/python/app_api.py
- apis/app-api/python/test_app_api.py
- apis/app-api/rust/Cargo.toml
- apis/app-api/rust/src/lib.rs
- apis/app-api/rust/src/query.rs
- apis/app-api/rust/src/tests/mod.rs
- apis/app-api/rust/src/tests/query.rs
- apis/pumpkin-mcu-api/mcu_api.py
- tools/dist/Dockerfile
Updated the Rust and Python app APIs to do graphql requests over http instead of udp.
Also in this PR:
- Added a new flag `PKG_CONFIG_ALLOW_CROSS` to circleci. The Rust app API updates brought in a crate which needs the flag in order to be able to cross-compile
- Updated circleci config to use Python3 for everything
- Fixing some python unit tests
- Updating our Dockerfile to include the new python dependency (`responses`)
> Updating the app APIs to query via HTTP

- Cargo.lock
- docs/services/comms-framework.rst
- examples/serial-comms-service/README.md
- libs/comms-service/Cargo.toml
- libs/comms-service/src/config.rs
- libs/comms-service/src/lib.rs
- libs/comms-service/src/service.rs
- libs/comms-service/tests/concurrent.rs
- libs/comms-service/tests/downlink.rs
- libs/comms-service/tests/query_service.rs
- libs/comms-service/tests/uplink.rs
- libs/comms-service/tests/util/mod.rs
- Adds integration tests around uplink and downlink behaviour
- Modifies uplink behaviour to allow communication with HTTP-based services
- Removes `handler_port_min/max` in favor of `max_num_handlers`
> Modify comms-service to allow HTTP transactions

- Cargo.lock
- Cargo.toml
- libs/comms-service/Cargo.toml
- libs/comms-service/tests/concurrent.rs
- libs/comms-service/tests/query_service.rs
- utils/Cargo.toml
- utils/src/lib.rs
- utils/src/testing.rs
In the process of #318 we wanted a test against one of our actual services. This was initially done in a way very specific to that service, but seems like a useful thing for other integration tests.
This PR pulls out that work and is the beginning of a method for writing integration tests which interact directly with other binary crates.
> Creating generic service testing utility

- services/app-service/src/schema.rs
- services/app-service/src/tests/mod.rs
- services/iobc-supervisor-service/src/main.rs
- services/iobc-supervisor-service/src/schema.rs
- services/pumpkin-mcu-service/service/schema.py
- services/telemetry-service/src/main.rs
- services/telemetry-service/src/schema.rs
- services/telemetry-service/tests/test_ping.rs
A few of our services don't include the "ping" query. It's super nice to have, so I'm adding it.
> Adding 'ping' query to all services

- apis/telemetry-db-api/src/lib.rs
The telemetry database uses fractional seconds since UNIX epoch for its timestamps. Basically everywhere, this value is stored as a double.
This PR fixes the one remaining place that it's still an integer value.
> Correcting telem db table creation

- services/app-service/src/registry.rs
- services/app-service/src/tests/register_app.rs
- services/app-service/tests/test_uninstall.rs
1. If the last version of an app is uninstalled, its active symlink will now be removed
2. If, for some reason, the active symlink directory stops existing, it will be recreated during the next app registration
> Improving app service edge cases

- services/app-service/src/registry.rs
- services/app-service/tests/test_python_app.rs
- services/app-service/tests/test_rust_app.rs
- services/app-service/tests/utils/python-proj/main.py
- services/app-service/tests/utils/python-proj/sub/sub.py
- services/app-service/tests/utils/rust-proj/src/main.rs
- services/app-service/tests/utils/rust-proj/testfile
When registering an application, we currently copy the entire given directory. This allows users to register an app with multiple files. This is mostly important for Python, but does also give the user the ability to include auxiliary files (ex. a custom config file for something).
This PR updates the app service to change its working directory to the specified application's directory before kicking it off during a ``startApp`` request. This allows users to specify the files they included with their app using relative paths.
Note: Multi-file Python actually works without the app service changes, but I did expand the Python test project in order to verify this
> Updating the app service to change to app's dir before kicking it off

- docs/obc-docs/porting-kubos.rst
This doc glosses over *alot* of the finer details to get KubOS up and running on a new board, but covers all the high-level items that need to be created.
> Adding high-level porting doc

- apis/isis-imtq-api/test/imtq/imtq.c
- apis/system-api/tests/test_boot_vars.rs
- libs/cbor-protocol/src/lib.rs
- services/app-service/src/registry.rs
- services/app-service/tests/utils/mod.rs
- tools/ci_c.py
We have a few unit tests that fail periodically. This PR attempts to fix them
- Updating boot vars tests to use a randomly generated temporary directory rather than just `/tmp`
- Updating boot var tests to add a little time between setting a variable and then fetching it
- Expanding the delay for the iMTQ watchdog tests
- Making all CBOR doc examples `no_run`
- Tweaking the way we change the current directory for running apps
- Adding retry logic to the app service test setup
> Fixing intermittently failing CI tests

- docs/os-docs/kubos-linux-on-bbb.rst
- docs/os-docs/kubos-linux-on-iobc.rst
- docs/os-docs/kubos-linux-on-mbm2.rst
With kubos/kubos-linux-build#174, the iOBC's SD card image is now automatically created as part of the build process. This PR updates the iOBC build docs to remove the need to manually create the image.
Also updating a few buildroot version numbers that got missed
> Updating iOBC build doc for image autogen

- libs/comms-service/src/service.rs
- libs/comms-service/tests/uplink.rs
UDP pass through is implemented one way from ground to flight services. We are currently assuming that any responses will be passed through the downlink port.
> Adding udp passthrough to comms service.

- .circleci/config.yml
- Cargo.toml
Adding two new compiler options for Rust project release builds:
- `opt-size = "z"` - Tells the compiler to optimize for size as much as possible
- `codegen-units = 1` - Tells the compiler not to build in parallel. Building in parallel prevents the compiler from being able to do certain optimizations
I compared the size of the application service's binary when compiled for the iOBC using the release build profile.
Old size: 4,360,632
Adding opt-level z: 3,677,904
(prev) + codegen-units 1: 3,423,072
Diff: -937,560 (-21.5%)
Old size + arm-linux-strip: 2,602,756
New size + arm-linux-strip: 1,496,836
Diff: -1,105,920 (-42.5%)
> Improving Rust size optimization for release builds

- tools/dist/Dockerfile
When I tried to regenerate our Docker image, it failed because the latest version of `breathe` only supports Python3. I have locked it at the last Python2.7-friendly version and created a couple cards to migrate everything to Python3 in the future.
There are two other lines which I added while messing with things that I would like to leave in:
- Upgrading pip to the latest version - This is just because the default version is super old
- Upgrade setuptools to the latest version - I ran into issues when installing `sphinxcontrib-plantuml` for Python3. It threw a really weird (non-obvious) error. A google search led me to conclude that `setuptools` needed to be updated.
> Locking version of breathe until we fully migrate to Python3

- docs/obc-docs/cross-compile.rst
Adding instructions for setting up cross-compiling in a local dev environment, rather than the SDK.
The SDK docs already have some information about cross-compiling, but I'm leaving that where it is for now. Once the dust settles (or if someone has a better idea), the information might get moved around.
> Adding instructions for local cross-compile

- apis/app-api/rust/src/framework.rs
- apis/system-api/src/config.rs
- examples/python-mission-application/mission-app.py
- examples/python-mission-framework/python-mission-app.py
- examples/rust-mission-app/src/main.rs
- services/app-service/tests/utils/python-proj/main.py
- Updated the rust app api to allow the `-c config` option
- Updated the rust system-api to allow the `-r level` option (not that it will be used by that crate, but it was the easiest/fastest way to fix this issue. The `getopt` crate does not have a way to allow unknown args. We might want to migrate to something like `clap` in the future)
- Updated the python examples to get and set the non-default config value
Doc updates will be done in a separate PR (against the doc-reorg branch)
> Updating Rust app API and example apps to allow custom config file

- services/app-service/src/registry.rs
- services/app-service/src/schema.rs
- services/app-service/src/tests/registry_start_app.rs
- services/app-service/tests/test_rust_app.rs
- services/app-service/tests/utils/rust-proj/config.toml
- services/app-service/tests/utils/rust-proj/src/main.rs
If you want to play with KubOS locally, you need to be able to start an app with the app service using a custom config file.
This PR adds a new schema arg, ``config``, to do so.
Docs will be updated in a separate PR
> Adding ability to start app with custom config file

- docs/sdk-docs/sdk-rust.rst
depends on kubos/cargo-kubos#4
> updated cross-compile docs to use `cargo kubos`

- docs/tutorials/app-register.rst
- docs/tutorials/first-mission-app.rst
- docs/tutorials/first-obc-project.rst
- examples/python-mission-application/mission-app.py
- examples/python-mission-framework/python-mission-app.py
The monitor service relies on `/proc/meminfo` in order to query the system's available memory. OSX doesn't have this file, which means that the first mission app tutorial doesn't work for Mac users.
Tweaking the app to just do a `{ping}` query instead
> Tweaking first mission app to be compatible with OSX

- Cargo.lock
- apis/nosengine-rust/Cargo.toml
- apis/nosengine-rust/build.rs
- apis/nosengine-rust/nosengine_c_interface/CMakeLists.txt
- apis/nosengine-rust/src/client/i2c.rs
- apis/nosengine-rust/src/client/mod.rs
- apis/nosengine-rust/src/client/spi.rs
- apis/nosengine-rust/src/client/uart.rs
- apis/nosengine-rust/src/ffi/i2c.rs
- apis/nosengine-rust/src/ffi/mod.rs
- apis/nosengine-rust/src/ffi/spi.rs
- apis/nosengine-rust/src/ffi/uart.rs
- apis/nosengine-rust/src/lib.rs
- apis/novatel-oem6-api/Cargo.toml
- apis/novatel-oem6-api/examples/gps-test.rs
- apis/novatel-oem6-api/src/messages/commands/log.rs
- apis/novatel-oem6-api/src/messages/commands/mod.rs
- apis/novatel-oem6-api/src/messages/commands/unlog.rs
- apis/novatel-oem6-api/src/messages/logs/best_xyz.rs
- apis/novatel-oem6-api/src/messages/mod.rs
- apis/novatel-oem6-api/src/oem6.rs
- hal/rust-hal/SimConfig.toml
- hal/rust-hal/rust-i2c/Cargo.toml
- hal/rust-hal/rust-i2c/src/lib.rs
- hal/rust-hal/rust-uart/Cargo.toml
- hal/rust-hal/rust-uart/src/error.rs
- hal/rust-hal/rust-uart/src/lib.rs
- services/novatel-oem6-service/Cargo.toml
- services/novatel-oem6-service/src/model.rs
Enables the novatel oem6 service/api to conditionally compile (`--features nos3`) support for NOS3's gps sim.
- NOS3 Novatel oem615 sim *ONLY* supports `log <...>` and `unlog <...>` and for `bestxyza`
- Novatel service queries and mutations relying on anything other than bestxyza logs are not supported
- To set up, configure nos3 gps sim to send only binary logs
- Changes to the `novatel_oem6_api` enable it to send ascii commands to the nos3 gps sim (nos3 only understands ascii)
> Novatel OEM6 GPS NOS3 Sim Support

- Cargo.lock
- apis/system-api/Cargo.toml
- apis/system-api/src/config.rs
- services/app-service/src/main.rs
- services/clyde-3g-eps-service/src/main.rs
- services/isis-ants-service/src/main.rs
- services/kubos-service/src/service.rs
- services/local-comms-service/src/main.rs
- services/novatel-oem6-service/src/main.rs
- services/nsl-duplex-d2-comms-service/src/main.rs
- services/shell-service/src/main.rs
- services/telemetry-service/src/main.rs
This PR fixes two bugs which slipped through the cracks of our CI tests:
- When the services start up, they attempt to read various config options. There is currently `ok_or()` logic to log an error message and then exit the service. `ok_or()` is "eagerly evaluated" by the Rust compiler, so the error message ends up _always_ getting logged, even if the config fetch succeeded.
- Migrating to `ok_or_else` instead to avoid this problem
- Problem wasn't caught by CI because we don't verify logging
- Our config parsing logic currently uses `getopts` to parse the command line options and look for the `-c {config.toml}` argument. Now that config parsing no longer silently fails and takes defaults, the init system is failing to start the app service. It tries to call `kubos-app-service -b` to …
> Service logging fix + app service OnBoot fix

- Cargo.lock
- services/scheduler-service/Cargo.toml
- services/scheduler-service/src/main.rs
- services/scheduler-service/src/objects.rs
- services/scheduler-service/src/scheduler.rs
- services/scheduler-service/src/schema.rs
- services/scheduler-service/tests/mutations.rs
- services/scheduler-service/tests/remove.rs
- services/scheduler-service/tests/util/mod.rs
- utils/Cargo.toml
- utils/src/testing.rs
Adds implementations for the following mutations:
- `register` - Registering a new schedule
- `activate` - Activating an existing schedule
> Scheduler mutations

- Cargo.lock
- docs/ecosystem/linux-docs/logging.rst
- docs/ecosystem/services/telemetry-db.rst
- services/telemetry-service/Cargo.toml
- services/telemetry-service/src/udp.rs
- services/telemetry-service/tests/test_udp.rs
If telemetry entries come wrapped in an array over UDP, they are all imported.
What's the best way to write a test that asserts error logs?
> Allow bulk telemetry over UDP

- Cargo.lock
- apis/isis-ants-api/src/ants.rs
- services/isis-ants-service/src/main.rs
- services/isis-ants-service/src/model.rs
- services/isis-ants-service/src/objects.rs
- services/isis-ants-service/src/schema.rs
- services/isis-ants-service/src/tests/mod.rs
- services/isis-ants-service/src/tests/mutations/errors.rs
- services/isis-ants-service/src/tests/mutations/test_hardware.rs
- services/isis-ants-service/src/tests/queries/deployment_status.rs
- services/isis-ants-service/src/tests/queries/errors.rs
- test/integration/linux/isis-ants/Cargo.toml
- test/integration/linux/isis-ants/src/main.rs
- tools/default_config.toml
Primary change: The ISIS antenna service now initiates the `AntS` structure inside a mutex. Previously we were allowing it to be cloned, which lead to the HTTP server cloning the structure, doing its GraphQL query work, then dropping the clone. This clone triggered the `AntS::Drop()` logic, which closes the I2C connection, preventing any further communication with the underlying device.
Auxiliary changes: Bringing code up to rust 1.37 standards, disallowing warnings
> Fixing ISIS antenna structure ownership

- Cargo.lock
- services/scheduler-service/Cargo.toml
- services/scheduler-service/src/config.rs
- services/scheduler-service/src/file.rs
- services/scheduler-service/src/main.rs
- services/scheduler-service/src/scheduler.rs
- services/scheduler-service/src/schema.rs
- services/scheduler-service/tests/activate.rs
- services/scheduler-service/tests/init.rs
- Refactored `tokio` usage to give us a single runtime in a single thread. This enabled to creation of `stop` to stop an active schedule and all scheduled tasks. Addresses naive implementation found in #465.
- Implementing starting or restarting the active schedule upon activating a schedule.
- Extracted `config.rs` for `ScheduleConfig` related structures and parsing function.
- Extracted `file.rs` for `ScheduleFile` related things, and functions which deal with manipulating on disk schedule files.
- Distilled `scheduler.rs` down to functions and structures solely related to running the actual schedule and executing app tasks.
> Scheduler tokio + general refactor

- clients/kubos-file-client/README.rst
- clients/kubos-file-client/src/main.rs
- docs/tutorials/file-transfer.rst
- services/file-service/src/lib.rs
- File service now logs a message if config file is missing
- File service and file client will now run on compatible, default ip/port values if not specified
- Adjusted default chunk size in file service to match client
> File service + client fixes

- Cargo.lock
- services/kubos-service/Cargo.toml
Pinning the version of `pkg-config` to `0.3.15` to avoid introduction of `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS` default usage by `0.3.16`.
The `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS` flag is currently breaking the kubos linux build.
> Pinning pkg-config crate version

- Cargo.lock
- clients/uart-comms-client/Cargo.toml
- libs/comms-service/Cargo.toml
This [issue](https://github.com/libpnet/libpnet/issues/391) is causing problems in the `cargo install` step of our vagrant provisioning. Bumping pnet to `0.23.0` resolves the issue.
> Bumping pnet to 0.23.0

- .gitignore
- examples/rust-mission-app/README.rst
- examples/rust-mission-app/src/main.rs
I ran into issues running this in the SDK, first because I didn't realize that it required a config file, and second because it was logging connection errors to the monitor service when it was really the telemetry service.
https://github.com/kubos/kubos/tree/master/examples/rust-mission-app
> Fix incorrect debug logs from rust-mission-app

- services/app-service/tests/test_apps.rs
- services/app-service/tests/test_kill.rs
- services/app-service/tests/test_monitor.rs
- services/app-service/tests/test_python_app.rs
- services/app-service/tests/test_rust_app.rs
- services/app-service/tests/test_uninstall.rs
- services/app-service/tests/utils/mod.rs
- services/telemetry-service/tests/test_delete.rs
- services/telemetry-service/tests/test_empty_db.rs
- services/telemetry-service/tests/test_filter_parameter.rs
- services/telemetry-service/tests/test_filter_subsystem.rs
- services/telemetry-service/tests/test_filter_timestamp.rs
- services/telemetry-service/tests/test_insert.rs
- services/telemetry-service/tests/test_insert_bulk.rs
- services/telemetry-service/tests/test_limit.rs
- services/telemetry-service/tests/test_ping.rs
- services/telemetry-service/tests/test_route.rs
- services/telemetry-service/tests/test_select_all.rs
- services/telemetry-service/tests/test_udp.rs
- services/telemetry-service/tests/utils/mod.rs
The app and telemetry service unit tests currently use a custom `teardown` function to clean up at the end of a test. Converting them to use the standard Rust `drop` function that way they don't have to be explicitly called
> Updating app and telemetry service unit tests to use Drop

- clients/kubos-file-client/src/main.rs
- docs/ecosystem/services/file.rst
- docs/tutorials/file-transfer.rst
- libs/file-protocol/src/lib.rs
- libs/file-protocol/src/protocol.rs
- libs/file-protocol/src/storage.rs
- services/file-service/src/lib.rs
- services/file-service/tests/common/mod.rs
- test/integration/large_download/src/main.rs
- test/integration/large_upload/src/main.rs
New control options:
- `hash_chunk_size` - Controls the chunk size used when hashing the file.
- `inter_chunk_delay` - Controls the delay between transmission of individual chunks
- `max_chunks_transmit` - Controls maximum number of chunks to transmit before waiting on response
Also:
- Cleaned up kubos-file-client a bit.
- Renamed original `chunk_size` to `transfer_chunk_size`
> Added new options for controlling the file protocol

- services/scheduler-service/src/app.rs
When kicking off an app, the app service [waits 300ms](https://github.com/kubos/kubos/blob/master/services/app-service/src/registry.rs#L722) to see if the app immediately returns before returning its GraphQL response.
The scheduler is currently only waiting 200ms to hear back from the app service.
The PR bumps the scheduler's wait time to better match the app service's behavior
> Increasing scheduler 'start app' response wait time to match app service

- docs/getting-started/local-setup.rst
Fixes #546: Update local setup docs to use rust version to 1.39.0
> Update reference to rust version in local setup from 1.32.0 to 1.39.0

- libs/comms-service/Cargo.toml
- libs/comms-service/src/lib.rs
- libs/comms-service/src/packet.rs
- libs/comms-service/src/service.rs
- libs/comms-service/src/telemetry.rs
We would like a version of the comms service framework which only handles UDP traffic. These changes place the functionality for handling GraphQL traffic behind a feature. 
Currently the feature is enabled by default but can be easily disabled in the `Cargo.toml` like so:
```toml
[dependencies]
comms-service = { path = "path/to/comms-service", default-features = false }
```
> Feature gating GraphQL functionality

- libs/comms-service/src/spacepacket.rs
vec.append consumes another vec. The payload had to be cloned to be
consumed, Then the elements are "moved" (copied) into the vec. (2 copies)
vec.extend does not consume the provided slice, only copies the elements
to the end of the vec. (1 copy)
> Unnecessary clone of payload data when creating raw spacepacket

- libs/comms-service/src/service.rs
This the CommsControlBlock can still be used in the same way as before
by setting the type parameter of WriteConnection and ReadConnection to
the same type and using one Arc<Mutex<..>>. The allows the read/write
threads to mutually lock each-other like before.
In the other case, Two separate types can be used, two separate
Arc<Mutex<..>> (Possibly don't need the mutex) allow the read/write
threads to operate independently of each-other.
Technically this is a breaking change so maybe bump the minor version of libs/comms-service?
> Add a second type paramter allowing seperate Read/Wrtie Connections in the CommsControlBlock

- Cargo.lock
- libs/comms-service/Cargo.toml
The comms-service had a reference to the older version of Juniper version 0.9.2. This was the only usage of that version in KubOS.
Package tests pass after updating to juniper:0.11.1
> Consolidate all Juniper package versions to 0.11.1

- docs/ecosystem/services/monitor-service.rst
- services/monitor-service/src/loadavg.rs
- services/monitor-service/src/main.rs
- services/monitor-service/src/objects.rs
- services/monitor-service/src/schema.rs
The ``loadAvg`` query can be used to get information about the system's processor utilization. It operates by reading `/proc/loadavg` and parsing available values to return averaged processor load, counts of active processes, and last process ID status.
Open to suggestions on naming and pattern. I primarily followed the MemInfo monitor as example.
> Monitor Service loadavg

- .cargo/config.toml
- .circleci/config.yml
- Cross.toml
- tools/dist/Dockerfile
- tools/dist/Dockerfile.aarch64
[cross][] seems to be the new all-in-one cross compile front end for Cargo.. it supports Docker out of the box and has some really nice default images. I found setting up `aarch64` builds a breeze, and wasted hours trying to set it up with our current container `kubos/kubos-dev` without success.
I'm wondering if we should move fully to cross for our custom toolchains eventually too.. or just get rid of them. hmmm food for thought :)
basic usage:
1. install [cross][]
1. `cross build --target=aarch64-unknown-linux-gnu`
2. see all the aarch64 binaries under `target`!
[cross]: https://github.com/cross-rs/cross#installation
> add support for cross-rs compatible aarch64 builds
