targets/target-msp430f5529-gcc/mspdebug/debug.sh
targets/target-msp430f5529-gcc/target.json

Very basic debugging script for the msp430f5529 target.

KUBOS-187 Add debug script for the msp430f5529 target

---

test/integration/test_cli.py

Quick and dirty fix for a broken test. Going to merge this now to test Jenkins.

Updated CLI test

---

libcsp/doc/interfaces.md

Interfaces doc ends abruptly. Copied back from the GomSpace repo converting from rst to md.
// cc @kubostech/devs

CSP Doc Fix 

---

telemetry-aggregator/module.json
telemetry-aggregator/source/aggregator.c
telemetry-aggregator/telemetry-aggregator/aggregator.h
telemetry/source/telemetry.c
telemetry/telemetry/destinations.h

A basic data aggregation layer for telemetry
* Currently no automatic data polling
* Provides a stub function for users to implement with their sensor polling/data submission
* User function is run in loop with user configurable delay
* Provides helper function for telemetry submission 
CC: @kyleparrott @cnalley @kubostech/devs

Basic aggregator for telemetry

---

Jenkinsfile

Adding a Jenkinsfile to make a multibranch pipeline.

Multibranch

---

Jenkinsfile

Boot up a single useable Jenkinsfile. Actual functionality to be added in later PRs.

Add Multibranch Jenkins Project

---

Jenkinsfile
test/integration/test_raspi.py

Getting the git repo & a basic python script running on the raspi.

Add python job to jenkins

---

hal/kubos-hal-stm32f4/source/uart.c

Revert "KUBOS-206 STM32F4 HAL changes for receiving CSP packets over UART"

---

libcsp/CMakeLists.txt
libcsp/include/csp/drivers/socket.h
libcsp/include/csp/interfaces/csp_if_socket.h
libcsp/src/drivers/socket/socket_linux.c
libcsp/src/interfaces/csp_if_socket.c

As part of [KUBOS-350](https://kubostech.atlassian.net/browse/KUBOS-350) CSP needs the ability to communicate with other processes running in a Linux system.

[KUBOS-350] Adding a socket interface to CSP

---

docs/changelog.md

Created a high-level list of everything we've done since October...
**NOTE:** This does not include CIStack or the Dashboard.  Wasn't sure a) if they should be included here and b) how they should be listed
@kubostech/devs

Created initial v0.2 changelog list

---

.gitignore
docs/Doxyfile
docs/contribution-process.md
docs/kubos-development.md
docs/kubos-linux-on-iobc.md
docs/msp430-launchpad-guide.md
docs/sdk-cheatsheet.md
docs/sdk-reference.md
docs/stm32f4-discovery-board-guide.md
docs/user-app-on-iobc.md

Adding/updating table of contents and intra-file linking
- Note: Some of the header link names don't match the headers.  There was some weirdness getting doxygen to generate the links correctly as-is, so I ended up renaming some of them...
Fixing image/iOBC paths
Fixing file links

v0.2 Doc Fixes

---

docs/first-project.md

Fixed incorrect Github url in first-project.md
Fix for #47

Github-47 Fixed Documentation Bug

---

docs/kubos-linux-on-iobc.md

There were extraneous '--s' characters.

Removing extra characters from around images

---

targets/target-kubos-linux-isis-gcc/minicom/flash.sh

Updating the ISIS target's flash script to check for the *.itb file extension.  If found, it will load the file into the new /upgrade partition and set the new kubos_updatefile environment variable with the new file name.
Also, migrating user applications from /usr/bin into /home/usr/bin so that they will live in the new userspace partition, rather than the rootfs.

[KUBOS-325] Adding detection and routing for flashing KubOS Linux upgrade packages

---

docs/kubos-linux-on-iobc.md
docs/kubos-linux-upgrade.md
docs/main.md

Created a new document to cover KubOS Linux upgrade package creation, installation, and rollback.

[KUBOS-326] Remote Update Doc

---

commands/Makefile
commands/core.c

This implementation is eventually going to get converted into a traditional kubos-linux command project format (when that exists and those builds are supported) rather than this single source file/Makefile configuration.
There's also plans to move the argument parsing to argp when more than one command is implemented  😄

KUBOS-396 Ping command

---

docs/user-app-on-iobc.md
targets/target-kubos-linux-isis-gcc/minicom/flash.sh
targets/target-kubos-linux-isis-gcc/target.json

Added three new config.json fields:
* system.initAfterFlash - default False. Option for user to specify that their application should be started after being flashed.
* system.initAtBoot - default True. Option for user to specify that their application should be started at boottime
* system.runLevel - default 50 (val 10-99). Sets initialization order value relative to other userland init scripts.
If initAtBoot is set, an init script will be created ("S{runLevel}{appName}") and installed into /home/etc/init.d
Note: In order to work, the kubostech/kubos-linux-build#13 PR needs to be merged.

[KUBOS-340] App init script generation/installation

---

linux-telemetry-service/config.json
linux-telemetry-service/module.json
linux-telemetry-service/source/main.c
services/telemetry/telemetry-linux/source/server.c

* Executable telemetry service for the linux environment
* Most basic level of functionality, allows for subscribers and publishers, but does not come with any built-in

[KUBOS-350] Linux telemetry service

---

test/integration/jenkinsnode/cistack/binfile.py
test/integration/jenkinsnode/cistack/utils.py

Specific fix for Dave. May make sense to leave this branch open as there will likely be more bug fixing to do.

Added specific errstr variable for binfile.py

---

docs/sdk-installing.md
docs/sdk-reference.md
docs/sdk-upgrading.md

This addresses some formatting, spelling, and new options that haven't been documented in the sdk docs.

KUBOS-435 Kubos-SDK Doc updates

---

docs/sdk-installing.md

Lots of general doc clean up and improvements.

KUBOS-458 Updating per pre1.0 doc audit

---

docs/contribution-process.md

- Add link to coding standards doc
- Create a Pull Request
- Mention that creating Pull Requests early is appreciated, just mark as '[WIP]'
- Create a Pull Request - Typo "'name}'"
- Add section for automated testing

[KUBOS-464] Updating contribution doc

---

docs/working-with-the-iobc.md

Adding basic overview for using the iOBC's peripheral pins

[KUBOS-467] Adding iobc peripheral usage

---

docs/Doxyfile
docs/kubos-arch.md
docs/kubos-linux-overview.md
docs/main.md

This PR is a proof-of-concept showing how to generate diagrams within Doxygen and giving a few examples of what those diagrams can look like.
Doxygen has a few different ways of generating diagrams, the two methods I used are DOT and msgcen.
[DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) is a language used to describe graphs. Doxygen uses [Graphviz](http://www.graphviz.org/) to parse and render the DOT graphs.
[Mscgen](http://www.mcternan.me.uk/mscgen/) is a utility designed for generating sequence charts/diagrams.
Here are the end result diagrams...
Boot-up UML diagram
[Relevant Mscgen markup](https://github.com/kubostech/kubos/compare/doxygen_search...doxygen_diagram_test?expand=1#diff-7de8f5736bee4626a85b4ba29be5a101R16)
Boot-up with storage flow
[Relevant DOT …

Doxygen Diagrams

---

docs/sdk-installing.md

KUBOS-483 Documenting the usergroup addition command for linux hosts during sdk

---

docs/linux-docs/working-with-the-bbb.rst
docs/linux-docs/working-with-the-mbm2.rst

As per https://github.com/kubostech/kubos-linux-build/pull/71

Update default IP for beaglebone/mbm2
