kubos/kubos

vm/Vagrantfile

I messed up yesterday and switched to an incorrect version of the toolchain in the provisioning script. The missing -y option on the `add-apt-repository` command wasn't actually adding those repos for some reason (it was in the docker builds) and wasn't finding those packages as a result. This PR fixes that mistake and reverts to the correct toolchain package.

Fix adding ppa -y option. Install correct arm-none-eabi toolchain.

---

targets/target-stm32f407-disco-gcc/openocd/flash.sh
targets/target-stm32f407-disco-gcc/target.json

Very basic debugging implementation for the stm32f4 discovery board.
I'm not crazy about the debugging implementation, specifically how openocd is started and not managed very well, or really at all by this implementation. It does work but should definitely be improved soon.

KUBOS-187 Adding Debug Configuration for the stm32f407 discovery target

---

.gitignore
telemetry/module.json
telemetry/source/telemetry.c
telemetry/telemetry/destinations.h
telemetry/telemetry/sources.h
telemetry/telemetry/telemetry.h

* Initial implementation of basic core telemetry interfaces.
* Single input interface
* Mechanism for CSP publish/ouput
* Simple telemetry_packet with basic routing info and single data type
* Example header files defining source & destination information
/CC: @kubostech/devs

Basic telemetry implementation

---

telemetry/source/telemetry.c
telemetry/telemetry/sources.h
telemetry/telemetry/telemetry.h

This PR adds a union data type to the telemetry packet struct and an enum for telemetry data types to allow destinations to decode which union member is being used. This is intended to start the discussion on the pros and cons of using a union to store telemetry data.
/cc @kubostech/devs

Telemetry Data Type

---

targets/target-msp430f5529-gcc/ld/memory.x

A user recently encountered a linking error:
```
ym/freertos/existing/freertos.a(port.c.o): In function `prvTickISR':
/usr/lib/yotta_modules/freertos/FreeRTOS/Source/portable/GCC/MSP430F5529/port.c:346: relocation truncated to fit: R_MSP430_16_PCREL against symbol `usCriticalNesting' defined in .data.usCriticalNesting section in ym/freertos/existing/freertos.a(port.c.o)
```
This particular error is repeated across multiple functions. Don't get distracted by this error appearing to originate from the FreeRTOS code.
After digging around in the customer's code I found that I could make the linking errors go away once a certain amount of code was commented out. After adding back and commenting out code, trying to find problematic sections, it started to seem like the problem was more with the …

Change to MSP430 linker map

---

hal/kubos-hal-stm32f4/source/uart.c

Plug the usart_callback back into the UART irq for the STM HAL to allow CSP packets to be received over UART.

KUBOS-206 STM32F4 HAL changes for receiving CSP packets over UART

---

targets/target-kubos-linux-isis-gcc/minicom/flash.sh
targets/target-kubos-linux-isis-gcc/target.json

Created the script to transfer the compiled KubOS Linux user application onto the iOBC.
The application will be copied into /usr/bin, so that it will be located in $PATH and therefore executable from the command line.

[KUBOS-335] Kubus flash command for kubos-linux-isis-gcc target

---

docs/cli-reference.md
docs/contribution-process.md
docs/first-project.md
docs/kubos-development.md
docs/kubos-linux-on-iobc.md
docs/kubos-linux-overview.md
docs/kubos-standards.md
docs/main.md
docs/msp430-launchpad-guide.md
docs/stm32f4-discovery-board-guide.md
docs/user-app-on-iobc.md

Making doc changes per Issue #39 
<details><summary>Checklist</summary>
<p>
for stories: follow standard 'as a [user]' format
mention linking to epics
we're making branches against master now
verify instructions still accurate
mention tagging people for review
mention WIP tag
*** Kubos linking description/instructions could probable use some going over.
*** A troubleshooting/FAQ doc could be good.
and then linking it in the Vagrantfile and running 'vagrant reload''
</p></details>

[KUBOS-365] Milestone 1 General Doc Updates

---

docs/sdk-reference.md
targets/target-kubos-linux-isis-gcc/minicom/flash.sh
targets/target-kubos-linux-isis-gcc/target.json

Added code to the iOBC flash script to allow us to detect and transfer non-application files.
I'm operating on the assumption that if the file requested for transfer does not match the project name, then it must not be the application binary. If so, then it will be transferred to the non-app directory location.
This destination can be customized by the user with a new config.json parameter "destDir". (I kind of dislike the variable name. Alternate suggestions would be appreciated)

[KUBOS-313] KubOS Linux Non-application File Transfer

---

cmd-control-client/cmd-control-client/client.h
cmd-control-client/source/command.c
cmd-control-client/source/main.c
cmd-control-client/source/parser.c
cmd-control-daemon/cmd-control-daemon/daemon.h
cmd-control-daemon/source/command.c
cmd-control-daemon/source/main.c
cmd-control-daemon/source/message.c
cmd-control-daemon/source/parser.c
command-and-control/command-and-control/types.h

The goal of this is to simplify the functionality of the daemon significantly and remove some of the ugly things needed to make the daemon work originally.
This is using the csp fifo interface through named pipes temporarily. This is not ideal, they are only for testing. **They will be removed before review is requested for this PR!**

KUBOS-398  Moving argument parsing into client

---

targets/target-kubos-linux-isis-gcc/target.json

This is a super simple addition to the isis target that was left out. This is included in the `x86-linux-native` [target](https://github.com/kubostech/kubos/blob/master/targets/target-x86-linux-native/target.json#L8). This allows target dependencies to apply for all linux targets without having to change the target dependency hierarchy.

Add missing similar-to keyword for the linux target.

---

cmd-control-client/config.json
cmd-control-client/source/main.c
cmd-control-daemon/cmd-control-daemon/daemon.h
cmd-control-daemon/config.json
cmd-control-daemon/source/main.c
command-and-control/command-and-control/types.h
commands/Makefile

This:
* Removes a couple of hard coded dev paths
* Moves some daemon specific defines out of the command-and-control module, and into the daemon
* Adds Config.jsons specific for getting the command and control framework running on the iOBC.

KUBOS-414 Moving daemon specific defines out of the command-and-control into daemon. Misc fixes for running on the iOBC

---

circle.yml
deploy.sh

This should create a new CD tag. 
CD tags contains a build field in the version number ie. Major.Minor.Patch.Build
Stable releases follow the shorter Major.Minor.Patch versioning scheme.

KUBOS-416 Continuous Delivery configuration for CircleCI

---

deploy.sh

This should only push the new CD tag and prevent any janky tag conflicts like [build 171](https://circleci.com/gh/kubostech/kubos/171)

Pushing only the new tag rather than all tags in the CD deploy script

---

docs/msp430-launchpad-guide.md

- Reference Documents
- Add hyphens to 'MSP430 Documentation' bullet points
- User's Guide and Launchpad User's Guide links are broken
- Pin Definitions - 'Quick Launch Guide' is a little vague (also 'Launchpad User's Guide')
- Flashing the board - Capitalization
- First sentence: 'Once you've built your project, you'll flash it onto your board using the micro-USB port.'
- change "'kubos flash'" to "`kubos flash`"

[KUBOS-456] MSP430 Guide updates from doc audit

---

docs/stm32f4-discovery-board-guide.md

- Pin Definitions 
- 'Within the user manual' - clarify which user manual
- Move 'within the source code' to the end
- 'Kubos SDK folder' -> 'project'
- Changing the pin definitions - mention that the project will need to be rebuilt to pull in the changes
- Flashing the board - Capitalization
- First sentence: 'Once you've built your project, you'll flash it onto your board using the mini-USB port.'
- change "'kubos flash'" to "`kubos flash`"
- Example Program
- "The Walkthrough" - fix header formatting

[KUBOS-460] STM32F4 Guide Updates

---

docs/first-project.md

<summary>first-project.md</summary>
- Capitalize all the section titles except 'your', 'a', and 'and'
- Prerequisites
- Remove 'create an instance of the kubos vagrant box [...]' since the 'Install the Kubos SDK' link is there and covers that.
- Remove or greatly shrink the blurb about mounting directories. Again, it's covered by the install doc.
- 'See the following [guide](link)' Make "guide" bold to make it slightly easier to notice that it's a link.
- Creating your project
- Change 'project files & folder' to 'project files and folders'
- 'a project cannot be named any of these words' -> 'which cannot be used as the name of the project'
- 'kubos-rt-example' - Turn into a hyperlink and link to the kubos-rt-example project
- Example list: capitalize i2c, spi, csp, and uart
- Create …

KUBOS-465 Making changes to first-project.md according the doc audit issue.

---

docs/sdk-reference.md
targets/target-kubos-linux-isis-gcc/minicom/flash.sh

Moving /home/{usr,etc,var} directories to be under /home/system/{usr,etc,var}. This keeps us within the Linux standard where everything under the /home directory belongs to a user. A new user 'system' is created in kubostech/kubos-linux-build#28
More docs will likely need to be updated, but are currently modified in atleast one other PR.

[KUBOS-466] Migrating system directories

---

docs/sdk-upgrading.md

<summary>sdk-upgrading.md</summary>
- Add instructions for upgrading SDK box?
- 'New updates will be announced on the Kubos website' - This isn't a thing that we're doing currently. What's the plan?
- Upgrading Kubos CLI - Missing 'vagrant up' step

KUBOS-468 Updating the sdk-updating.md document

---

cmd-control-client/source/command.c
cmd-control-client/source/parser.c
cmd-control-daemon/source/command.c
cmd-control-daemon/source/parser.c
command-and-control/command-and-control/types.h

This is the last bit of functionality to remove the library specific bits from C&C and get it running with the simplified executable interface.

KUBOS-457 Removing library command interface

---

.clang-format
docs/kubos-standards.md

Updating our standards doc to contain actual, fleshed out standards.
Also updated the .clang-format file to match these new standards.
Questions:
- C
- Implicit conversion to bool in conditions? ("if (ret)" vs "if (ret != NULL)")
- Each variable in own declaration?
- Returning: only allow return codes, or allow return values as well?
- Comments: only allow C style (/* */), or allow C++ style, too (//)
@kyleparrott, @plauche, @davesims, or really, anyone who actually knows and uses Python. I just put a link to the pep8 standard. I don't if we want to go into any more detail than that...

[KUBOS-469] Standards Doc Updates

---

freertos/config-msp430f5529/FreeRTOSConfig.h
targets/target-msp430f5529-gcc/CMake/toolchain.cmake
targets/target-msp430f5529-gcc/ld/memory.x
targets/target-msp430f5529-gcc/ld/memory_usbram.x

kubos-rt-example doesn't work on the MSP430F5529 anymore because the memory map was changed and is now too small.
I fixed it by copying all the MSP430 fixes from Marshall's PR #34

[KUBOS-490] Fixing RT Example on MSP430

---

docs/conf.py
docs/index.rst
docs/kubos-linux-upgrade.rst
docs/kubos-standards.rst

Created new docs/_static folder to house the tutorial video. Might want to pursue hosting videos elsewhere in the future.
Created in conjunction with issue #121 
Misc:
- Fixing standards doc headers to have correct levels
- Fixing random typo in upgrade doc

[KUBOS-486] Adding quick start tutorial to main page

---

tools/dist/Dockerfile
tools/dist/programs.json
tools/dist/version_check.py

Mirrors the Vagrant environment only for standard kubos projects (no linux dependencies).
This is a slightly stripped down (the linux dependencies have been removed) image that has been running in our CI builds for the kubos and kubos-linux-build repos.

KUBOS-520 Adding Kubos CI Dockerfile

---

deploy.sh

More than 1 digit in the build (and the patch) field broke the regex that classified tag types preventing tags from being pushed.

Fixing a bug in the version regex that incorrectly classified tag types

---

docs/kubos-linux-on-mbm2.rst
docs/working-with-the-mbm2.rst

Documenting the peripheral buses available to users with the Pumpkin MBM2 board

Pumpkin peripheral use documentation

---

examples/kubos-linux-example/README.md

I added the http:// extension to the documentation links and the 1.0.0 part after the hostname so that the links actually work

Fixed some errors in the documentation links

---

docs/kubos-linux-on-bbb.rst
docs/kubos-linux-on-mbm2.rst
docs/working-with-the-bbb.rst
docs/working-with-the-mbm2.rst

Updating documentation to remove the SPI0 bus from the Beaglebone Black documentation. It was removed from the board because the pins conflict with I2C1.
Also adding some small notes that have been in my head.

Removing SPI0 from BBB. Adding small doc updates

---

docs/working-with-the-bbb.rst

Typo in documentation. Replace write with read.

Typo in documentation

---

docs/first-linux-project.rst
docs/first-rt-project.rst

There were duplicate, incomplete instructions in the first project docs. I took out the duplicate instructions and just left the link to the setup doc, which includes the old instructions.

took out all prerequisites except the link to setting up the SDK

---

docs/faq-troubleshooting.rst
docs/sdk-installing.rst

As of v1.9.5, Vagrant now requires Windows operating systems to have at least Windows PowerShell v3.0. By default, Windows 7 SP1 comes with v2.0. I updated the docs to list the requirement and the steps necessary to upgrade PowerShell.
Sadly Windows Vista is no longer a supported OS, since it only supports up to PowerShell v2.0...

Documenting windows powershell requirement

---

docs/kubos-linux-on-bbb.rst
docs/kubos-linux-on-mbm2.rst

1. BBB buildroot config name is wrong
2. If currently running KubOS Linux, `umount` command must be run twice in order to successfully transfer the new SD image to the eMMC

Minor doc tweaks

---

docs/device-api/radio.rst
docs/device-api/radio_api.rst
radio/radio-api/radio-api/radio-struct.h
radio/radio-api/radio-api/radio.h

Passing generic pointers is bad. Passing pointers to context-specific structures is better.
Updating the generic radio API to include the appropriate specific radio API based on the `config.json` file so that quasi-generic radio structures can be used instead of generic pointers.
The TRXVU API will also be updated to reflect these changes.

Radio API - Moving away from generic pointers

---

deploy.sh

Currently we are producing release builds with the version format `major.minor.patch.build`. This is not quite compliant with how semantic versioning expects build numbers to be presented and causes issues when uploading docs for releases with a build number. PR changes format to `major.minor.patch+build`.

Changed release tagging script to use semver compliant build numbers.

---

docs/linux-docs/working-with-the-iobc.rst
test/integration/linux/bme280-spi/README.md
test/integration/linux/bme280-spi/module.json
test/integration/linux/bme280-spi/source/main.c
test/integration/linux/isis-obc/iobc-test-config.json

Support for SPI bus 1 on the iOBC has been added in kubostech/kubos-linux-build#76. This PR adds the accompanying docs and integration test.
Note: Also removing the now-deprecated tests from the iOBC's test config file

Adding doc and integration test for iOBC SPI bus 1

---

ccan/json/source/json.c

The JSON library's user-facing functions don't currently do any argument checking, which can lead to segfaults. This PR fixes that.
The user-facing functions are all the ones that start with `json_`, as seen in `ccan/json/json/json.h`

Adding null checking to user-facing JSON functions
